### ISSUE TITLE
test

### ISSUE THREAD

**Issue by munkhulzii** [munkhulzii/mage2-locale-mn-cyrl-mn#4]
test 
```
mysql:
    type: mysql:10.2
    disk: 2048

redis:
    type: redis:5.0

elasticsearch:
    type: elasticsearch:6.5
    disk: 1024
```
test

```
if (isAwesome){
      return true
    }
```

one more
